name: Build and Test Java Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11 using Temurin
      - name: Set up JDK 11 (Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Install dependencies and build the project
      - name: Install dependencies and Build
        run: ./gradlew clean build

      # Step 4: Run tests
      - name: Run Tests
        run: ./gradlew test
