name: Java Test with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurer Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Ajouter Gradle Wrapper
      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      # Exécuter les tests Gradle
      - name: Run Gradle tests
        run: ./gradlew test

      # Archiver les résultats JUnit
      - name: Archive JUnit test results
        uses: actions/upload-artifact@v3
        with:
          name: junit-results
          path: build/test-results/test/

      # Archiver le rapport Cucumber
      - name: Archive Cucumber report (if exists)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: reports/example-report.json
          
      # Vérifier si les artefacts ont bien été créés
      - name: List build directory for verification
        run: ls -R build/

              # Récupérer le code source 
      - name: Checkout code
        uses: actions/checkout@v4

      # Installer jq
      - name: Install jq
        run: sudo apt-get install -y jq

      # Vérifier le statut du Quality Gate
      - name: Check Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=inessBenguiar_GitActions-test" \
          | jq -r '.projectStatus.status')
          echo "Quality Gate Status: $STATUS"
          if [ "$STATUS" != "OK" ]; then
            echo "Quality Gate failed!"
            exit 1
          fi
          
      # Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurer Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Ajouter Gradle Wrapper
      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      # Exécuter la construction Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Générer Javadoc avec Gradle
      - name: Generate Javadoc
        run: ./gradlew javadoc

      # Archiver les fichiers JAR
      - name: Archive JAR artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-jars
          path: build/libs/*.jar

      # Archiver la documentation Javadoc
      - name: Archive Javadoc docs
        uses: actions/upload-artifact@v3
        with:
          name: build-docs
          path: build/docs/
          
      # Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurer Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Ajouter Gradle Wrapper
      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew



      - name: Déploiement du fichier jar sur myMavenRepo
        run: ./gradlew publish
        env:
          MYMAVENREPO_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MYMAVENREPO_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Slack notification
        uses: slackapi/slack-github-action@v1
        with:
          slack-message: ${{ github.workflow }} workflow ${{ job.status }}.
          View the run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send email notification on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Workflow ${{ github.workflow }} failed"
          body: "The workflow ${{ github.workflow }} has failed. View the run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions
          content_type: text/plain

      - name: Slack Notification
        uses: slackapi/slack-github-action@v1
        with:
          slack-message: "Build has completed successfully!"
          slack-token: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}


       

            

     

