name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is required for dependency submission

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Run Gradle tests
        run: ./gradlew test

      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results/

      - name: Generate and submit cucumber report
        run: |
          if [ -f "reports/example-report.json" ]; then
            echo "Cucumber report exists, processing it..."
            # Add any logic to handle cucumber reports if needed
          else
            echo "No cucumber report found."
          fi

      - name: Publish JUnit test results
        uses: actions/upload-artifact@v3
        with:
          name: junit-results
          path: build/test-results/test/TEST-Matrix.xml

