name: Build and Test Java Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11 (Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permissions to gradlew
        run: chmod +x ./gradlew

      - name: Install dependencies and Build
        run: ./gradlew clean build

      - name: Run Tests
        run: ./gradlew test
